name = "sideapp"
compatibility_date = "2025-09-19"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
format = "esm"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19mTUZTbV9wOVZMaHdWZFNRVG9aRlUiLCJhcGlfa2V5IjoiMDFLNUtFS0E1NlNHQ1ZGUllYRUFYUDVKMFYiLCJ0ZW5hbnRfaWQiOiJjZTc4ZmRkMjFjMGM2MjExYTgzZGM4NTk4MWVlYjY5ZDNjZGFlM2NiMWZmMTAzOTQ4YzA5NGFiOTMwYTFmMDBkIiwiaW50ZXJuYWxfc2VjcmV0IjoiMDZhZjQ5YjYtNTE4Mi00OWJmLTgxZTEtMjQ2Mjg1ZTYyNWFjIn0.r27ahHFck1C9QzOt4ZDtIJqCy8D5HsaaJj3QLN9azRg"
JWT_KEY="clicli123side"

[assets]
directory = "./public"